version: '3'

services:

  app:
    image: allanlee0724/sports:file
    container_name: sports
    ports:
      - 8080:8080
    environment:
      - VARIABLE=VALUE
    volumes:
      - ./logs/:/logs/

  loki: # Loki is a log aggregation tool
    image: grafana/loki:latest # think of this as a database for your logs
    container_name: logging-loki
    ports:
      - 3100:3100


  promtail:
    image: grafana/promtail:latest
    container_name: logging-promtail
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml # configuration I made:config saved in container
      - ./logs/staticLogs.log:/var/log/staticLogs.log # log we want to save:log in promtail
    command: "--config.file=/etc/promtail/promtail-config.yml"


  grafana:
    image: grafana/grafana:latest # default username/password:admin/admin
    container_name: logging-grafana
    # volumes:
    #   - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki # ensures loki is setup before Grafana tries to interface with it

  prometheus:
    image: prom/prometheus:latest # think of this as your database for your metrics over time
    ports:
      - 9090:9090
    volumes:
      # - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus-config.yml # passing the directory instead of just the config file for prometheus
    container_name: logging-prometheus
    command: "--config.file=/etc/prometheus/prometheus-config.yml" # We need to tell Prometheus what to target




 